### ISSUE TITLE
The `baseDomains`/`subDomains` separation is a bit confusing

### ISSUE THREAD

**Issue by szlend** [Janik-Haag/NixOS-DNS#7]
I feel like the `baseDomains`/`subDomains` separation is kind of confusing. I'm sure there's a good reason for it and it helps separating host configuration and modules, but It's hard to really understand without some example modules. The naming doesn't really help either because `subDomains` are not sub domains of `baseDomains`. I don't really have any better suggestions though. At least not without looking at some examples and understanding the intention better.

Imo the UX could also be improved a bit for people who don't write reusable modules for their host setups. At the moment it requires me to define all my domains twice, so I added this hack to my config:

```nix
config.networking.domains.subDomains = mapAttrs
  (_: _: mkDefault { })
  config.networking.domains.baseDomains;
```

I'm not sure whether that's a good idea or not, because I don't really understand the intent well enough.

Great module otherwise, by the way!

**Comment by Janik-Haag** [comment]
>  feel like the baseDomains/subDomains separation is kind of confusing.

I wouldn't say that's case but the naming might make it confusing.
Should have probably used something else, but now i'ts a bit too late since it would break existing configs.

> The naming doesn't really help either because subDomains are not sub domains of baseDomains

Can you elaborate a bit on that part?

> Imo the UX could also be improved a bit for people who don't write reusable modules for their host setups. At the moment it requires me to define all my domains twice, so I added this hack to my config:
> ```nix
> config.networking.domains.subDomains = mapAttrs
> (_: _: mkDefault { })
> config.networking.domains.baseDomains;
> ```

this seems a bit much.
So the way it's intended to be used is in baseDomains you basically "register" which zone apexs are available to the host.
This can be multiple domains like `example.com`, `example.org`, `my.domain.invalid`.
Any record you set here gets propagated into `networking.domains.subDomains` that match there base domain.

Let's say your basedomains look like this: 
```nix
  networking.domains = {
    "example.org" = {};
    "example.com" = {};
    "subdomain.example.com" = {};
  };
```
Then you will end up with two zone files, `example.com` and `example.org`.
And then in `networking.domains.subDomains` you add any subDomains.

Hope this helps clearing the confusion a bit.
Maybe adding something like `networking.domains.zones` would help which could then behave like the extraConfig module? 

> Great module otherwise, by the way!

Thank you <3

**Comment by szlend** [comment]
Today I gave this another shot on a new host and it just clicked. The record inheritance feels a bit magical, but it's convenient for sure. Thanks!
